export {
    LOGIN_URL,
    REGISTERATION_URL,
    UPDATE_PROFILE_URL,
    CHANGE_PASSWORD_URL,
    STATISTICS_URL,
    GET_ALL_SERVICES_URL,
    GET_ALL_USERS_URL,
    GET_ALL_GARAGES_URL,
    GET_OWNER_GARAGES_URL,
    GET_ALL_BOOKINGS_URL,
    GET_ALL_REGIONS_URL,
    GET_ALL_WILLAYATS_URL
} from "./ApiEndpoints";